---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
  namespace: default
data:
  client_config.json: |
    {
      "ClientID": "client1",
      "FrontEndAddr": "fe-get-svc.default.svc.cluster.local:80",
      "TracerServerAddr": "trc-svc.default.svc.cluster.local:80",
      "TracerSecret": ""
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  frontend_config.json: |
    {
      "ClientAPIListenAddr": ":8000",
      "StorageAPIListenAddr": "st-svc.default.svc.cluster.local:80",
      "TracerServerAddr": "trc-svc.default.svc.cluster.local:80",
      "TracerSecret": ""
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-config
data:
  storage_config.json: |
    {
      "StorageID": "storage1",
      "StorageAdd": ":8011",
      "FrontEndAddr": ":8001",
      "TracerServerAddr": "trc-svc.default.svc.cluster.local:80",
      "TracerSecret": "",
      "DiskPath": "/rpc-kvs/data"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracing-server-config
data:
  tracing_server_config.json: |
    {
        "ServerBind": ":6666",
        "Secret": "",
        "OutputFile": "trace_output.log",
        "ShivizOutputFile": "shiviz_output.log"
    }
